name: Hello Ansible

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner_label }}
    strategy:
      # if one job fails, other jobs will still try to complete
      fail-fast: false
      matrix:
        runner_label: [Homer, Marge]  

    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Echo runner label
        run: echo "Hello from runner labeled ${{ matrix.runner_label }}!"